### ISSUE TITLE
Sequencing a list of futures to insert elements

### ISSUE THREAD

**Issue by coreyauger** [mauricio/postgresql-async-app#1]
Hi I am looking to insert a record and a arbitrary number of foreign key related records as well in a transaction statement.

The code i have looks like this

``` scala
val future = conn.inTransaction {
            c =>
              c.sendPreparedStatement(insert,Array(dateTimeStr(), dateTimeStr(), occupants, uuid)).flatMap{
                r =>
                  r.rows match {
                    case Some(rs) =>
                      val id = rs.head("id").asInstanceOf[Long]
                      p.success(id)
                      Future.sequence(routes.map{
                        case (a, b, c) =>
                          c.sendPreparedStatement(insertRoutes,Array(a.toLong, id, b, c)
                      }.toList)
                    case None => throw new Exception("Insert into chat failed..")
                  }
              }
          }

```

I am getting an error of the following

```
17:29:43.388 [db-async-default-thread-1] ERROR c.g.m.a.d.p.PostgreSQLConnection:1 - Can't run query because there is one query pending already
```

I realize that I would normally form a chain of flatMaps .. but in this case were I have an arbitrary number of "routes" .. I am not sure how to compose this.

Any help on this would be appreciated.

**Comment by mauricio** [comment]
I haven't tried it myself, but something like:

``` sql
INSERT INTO films (code, title, did, date_prod, kind) VALUES
    ('B6717', 'Tampopo', 110, '1985-02-10', 'Comedy'),
    ('HG120', 'The Dinner Game', 140, DEFAULT, 'Comedy');
```

Should work for prepared statements, I think. You could make these many statements into a single one.

Also, the driver repo is [here](https://github.com/mauricio/postgresql-async), this repo is for the sample app only.

**Comment by coreyauger** [comment]
Thanks for the fast reply.  I will try it out and let you know.  Sorry for the repo confusion.. got lost ;)

**Comment by coreyauger** [comment]
Worked.  Thanks again!
